# Generated by Django 6.0 on 2026-01-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
